version: '3.7'
services:
  frontend:
    image: anwarsr/admin-frontend
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_admin
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app


  db:
    container_name: admin_db
    image: mysql:5.7.22
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: laravel_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - app
networks:
  app:

